### ISSUE TITLE
404 error with "ask a question" module

### ISSUE THREAD

**Issue by Gorneman** [ZiZuu-store/PrestaShop_module-CleanURLs#5] opened 2015-03-25 11:16 UTC
Hi, I've installed latest version and have a problem with this module.
https://www.prestashop.com/forums/topic/349333-module-gratuit-poser-une-question-sur-produit-captcha-1516/
when i click on "ask a question " button (link: http://www.mkup.it/module/okom_moreinfo/default?id_product=21&content_only=1&n=1) open a 404 error window frame.

**Comment by ZiZuu-store** [comment] 2015-03-25 11:27
Hi,
  having a quick look to your site it seems every URL with "module" is giving 404 /see the wishlist module for example ..

How you configured your routing? 
What PS version are you running?

**Comment by Gorneman** [comment] 2015-03-25 11:59
prestashop 1.6.0.14

**Comment by Gorneman** [comment] 2015-03-25 12:01
![routing](https://cloud.githubusercontent.com/assets/9078451/6824084/08194640-d2ef-11e4-9de0-807597b42939.jpg)

**Comment by ZiZuu-store** [comment] 2015-03-25 12:17
@Gorneman Sorry Domenico, we are still working to make the module work at best on PS 1.6.0.9 ..
Unfortunately we decided to maintain and go deeper in this module only a few days ago and there was a lot of idiosyncrasies in the code we are going to remove or rewrite.

I'm going to release a v0.8.1 in a few hours .. don't think it will solve, but you'll can test it ..  as we hardly want to make the module work in PS 1.6.0.14 (milestone v0.10) we will be happy to try to solve your issue if you could help us to point out the root cause ..

It seems everything is ok in your config .. try v0.8.1 as soon as it will be available

**Comment by Gorneman** [comment] 2015-03-25 12:51
Thanks for your work, Prestashop SEF urls are ugly and little useful. This module should be integrated in the core. i'll test new version.

**Comment by ZiZuu-store** [comment] 2015-03-25 14:51
v0.8.1 is out .. plz try asap thank you

**Comment by Gorneman** [comment] 2015-03-25 15:50
tested, same problem. Keep up the work. Thanks for the support and if you need, I can do some tests.

**Comment by ZiZuu-store** [comment] 2015-03-25 16:05
Ok. Unfortunately  it was the expected behaviour .. 

The problem is a change in the regex into the Dispatcher made by PS in versione 1.6.0.11 .. we received a pull request that "solved" the issue .. but overriding the Dispatcher to restore the old-regex is not a solution 

We are going deeper into the code to understand how to make the module behave well .. the proble should be with the "?" in the QS ..

Stay tuned .. can we communicate somehow more directly for testing? say a google hangout for example ..

regards

**Comment by ZiZuu-store** [comment] 2015-03-25 16:52
@Gorneman  Hi Domenico,

can you plz try the currend code? I'm confident it should have been fixed now ..

https://github.com/ZiZuu-store/PrestaShop_module-CleanURLs/archive/ZiZuu-CleanURLs.zip

If you confirm it works I'll release v0.9 shortly

**Comment by Gorneman** [comment] 2015-03-26 11:31
Installed and problem gone!Thanks

**Comment by ZiZuu-store** [comment] 2015-03-26 11:37
:) very well .. going to release a new version in a few hours

Thank you

**Closed** 2015-03-26 11:38 UTC
Labels: bug
